### ISSUE TITLE
FORMATTER_CRASH

### ISSUE THREAD

**Issue by nathany-copia** [cogini/logger_formatter_json#2]
Running locally, the first log entry I see is a FORMATTER_CRASH.

Elixir 1.17.3
Erlang 27.1.1
mac OS Sequoia 15

```
2024-10-03T10:11:32.174028-06:00 notice: FORMATTER CRASH: {report,#{label => {error_logger,info_report},report => [{alarm_handler,{set,{system_memory_high_watermark,[]}}}]}}
```

Maybe I haven't configured something correctly? I'm not sure.

If I use the standard logger, the first log is:
`10:12:28.616 [notice]     :alarm_handler: {:set, {:system_memory_high_watermark, []}}`

**Comment by reachfh** [comment]
I just made a new release that will likely fix it. Please upgrade to 0.8.4.

**Comment by nathany-copia** [comment]
It worked. Thank you!

```
{"msg":{"label":"{error_logger,info_report}","report":"[{alarm_handler,{set,{system_memory_high_watermark,[]}}}]"},"error_logger":{"tag":"info_report","type":"std_info"},"gl":"<0.244.0>","level":"notice","pid":"<0.248.0>","report_cb":"#Fun<error_logger.0.128667414>","time":1727984111078807}
```
